import React, { useMemo, useState } from "react";
import { Download, Printer, Save } from "lucide-react";

const modeName = (m) => m === "pipe" ? "Internal Circular Pipe" : m === "duct" ? "Non-Circular Duct / Channel" : "External Flow";
const fluidName = (f) => ({ water:"Water", air:"Air", ethyleneGlycol:"Ethylene Glycol", engineOil:"Engine Oil", custom:"Custom" }[f] || "Custom");
const fmt = (v,d=5) => { const x=Number(v); if(!Number.isFinite(x)) return "—"; if(Math.abs(x)>=1e6 || (Math.abs(x)>0 && Math.abs(x)<1e-4)) return x.toExponential(5); return x.toLocaleString(undefined,{maximumFractionDigits:d}); };

export default function ReynoldsEngineeringReport() {
  const [saved,setSaved]=useState(false);
  const report=useMemo(()=>{try{const x=localStorage.getItem("funda-reynolds-report");return x?JSON.parse(x):null;}catch{return null;}},[]);
  if(!report) return <main className="min-h-screen bg-slate-50 px-6 py-16"><div className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-8"><h1 className="text-2xl font-black">Reynolds Engineering Report</h1><p className="mt-3 text-slate-600">No calculation data was found. Generate the report from the Reynolds Number Calculator first.</p></div></main>;
  const {inputs:i,result:r,warnings=[],assumptions=[]}=report;
  const download=()=>{const rows=[["Parameter","Value","Unit"],["Mode",modeName(i.mode),"-"],["Fluid",fluidName(i.fluid),"-"],["Density",i.density,"kg/m³"],["Dynamic viscosity",i.viscosity,"Pa·s"],["Velocity",i.velocity,"m/s"],["Characteristic length",r.L,"m"],["Hydraulic diameter",r.Dh??"","m"],["Area",r.area??"","m²"],["Volumetric flow rate",r.Q??"","m³/s"],["Mass flow rate",r.mdot??"","kg/s"],["Kinematic viscosity",r.nu,"m²/s"],["Reynolds number",r.Re,"-"],["Flow regime",r.regime,"-"]];const csv=rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=u;a.download="funda-reynolds-engineering-report.csv";a.click();URL.revokeObjectURL(u);};
  const save=()=>{localStorage.setItem("funda-reynolds-report",JSON.stringify(report));setSaved(true);setTimeout(()=>setSaved(false),1800);};
  return <main className="min-h-screen bg-white px-6 py-10 text-slate-900 print:px-0 print:py-0"><div className="mx-auto max-w-5xl">
    <header className="border-b border-slate-300 pb-6"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-700">Funda Global Solutions</p><h1 className="mt-2 text-3xl font-black tracking-tight">Reynolds Number Engineering Report</h1><p className="mt-2 text-sm text-slate-500">{report.projectName}</p></div><div className="text-right text-xs text-slate-500"><p><b>Report Date:</b> {report.date}</p><p className="mt-1"><b>Client:</b> {report.clientName}</p></div></div><div className="mt-5 flex flex-wrap gap-2 print:hidden"><button onClick={save} className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-bold text-white"><Save size={16}/>{saved?"Saved":"Save Report"}</button><button onClick={download} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold"><Download size={16}/>CSV</button><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold"><Printer size={16}/>Generate PDF</button></div></header>
    <section className="mt-7"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">01</span>Executive Summary</h2><div className="mt-4 rounded-xl border border-cyan-200 bg-cyan-50 p-5"><p className="text-sm leading-6">The calculated Reynolds number is <b>{r.Re?.toPrecision(6)}</b> for <b>{modeName(i.mode)}</b>. The reported flow classification is <b>{r.regime}</b>.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-white p-4"><p className="text-xs text-slate-500">Reynolds Number</p><p className="mt-1 text-xl font-black">{r.Re?.toPrecision(6)}</p></div><div className="rounded-lg bg-white p-4"><p className="text-xs text-slate-500">Flow Regime</p><p className="mt-1 text-xl font-black">{r.regime}</p></div><div className="rounded-lg bg-white p-4"><p className="text-xs text-slate-500">Characteristic Length</p><p className="mt-1 text-xl font-black">{fmt(r.L,6)} m</p></div></div></div></section>
    <section className="mt-8"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">02</span>Input Conditions</h2><div className="mt-4 overflow-hidden rounded-xl border border-slate-200"><table className="w-full text-sm"><tbody>{[["Calculation Mode",modeName(i.mode),""],["Fluid",fluidName(i.fluid),""],["Density",fmt(i.density,5),"kg/m³"],["Dynamic Viscosity",Number(i.viscosity).toExponential(5),"Pa·s"],["Velocity",fmt(i.velocity,5),"m/s"],...(i.mode==="pipe"?[["Pipe Diameter",fmt(i.diameter,5),"m"]]:[]),...(i.mode==="duct"?[["Flow Area",fmt(i.area,6),"m²"],["Wetted Perimeter",fmt(i.wettedPerimeter,6),"m"]]:[]),...(i.mode==="external"?[["Characteristic Length",fmt(i.characteristicLength,5),"m"]]:[])].map(([a,b,c],idx)=><tr key={a} className={idx<6?"border-b border-slate-200":""}><td className="bg-slate-50 px-4 py-3 font-semibold">{a}</td><td className="px-4 py-3">{b} {c}</td></tr>)}</tbody></table></div></section>
    <section className="mt-8"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">03</span>Calculated Results</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Reynolds Number",r.Re?.toPrecision(6),""],["Flow Regime",r.regime,""],["Kinematic Viscosity",Number(r.nu).toExponential(5),"m²/s"],["Characteristic Length",fmt(r.L,6),"m"],["Volumetric Flow Rate",r.Q==null?"—":Number(r.Q).toExponential(5),r.Q==null?"":"m³/s"],["Mass Flow Rate",r.mdot==null?"—":fmt(r.mdot,6),r.mdot==null?"":"kg/s"]].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-lg font-black">{b} {c&&<span className="text-xs font-semibold text-slate-500">{c}</span>}</p></div>)}</div></section>
    <section className="mt-8"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">04</span>Methodology</h2><div className="mt-4 rounded-xl bg-slate-50 p-5"><p className="font-mono text-sm">Re = ρVL / μ = VL / ν</p><p className="mt-3 text-sm leading-6 text-slate-600">The calculation uses supplied density, velocity, dynamic viscosity and characteristic length. For a circular pipe L = D; for non-circular internal flow Dh = 4A/P; for external flow the supplied characteristic length is used.</p></div></section>
    <section className="mt-8"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">05</span>Engineering Checks</h2><div className="mt-4 space-y-3">{warnings.length?warnings.map((w,k)=><div key={k} className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6">{w.text}</div>):<div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm">No additional engineering checks were triggered.</div>}</div></section>
    <section className="mt-8"><h2 className="text-lg font-black"><span className="mr-2 text-xs text-cyan-700">06</span>Assumptions & Limitations</h2><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-5"><ul className="list-disc space-y-2 pl-5 text-sm leading-6">{assumptions.map((x,k)=><li key={k}>{x}</li>)}</ul></div></section>
    <footer className="mt-10 border-t border-slate-300 pt-5 text-xs text-slate-500">Funda Global Solutions — Engineering Simulation & AI Solutions</footer>
  </div></main>;
}
